M48
; DRILL file {KiCad 7.0.9+1} date Mon 11 Dec 2023 02:48:37 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-11T14:48:37+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X53.0Y-53.0
X53.0Y-67.0
X93.875Y-52.975
X94.175Y-66.775
T0
M30
